### ISSUE TITLE
Cosmix Live player not working for a number of channels

### ISSUE THREAD

**Issue by chiefkes** [OpenELEQ/unofficial-meta-players#9]
Several channels aren't showing up in meta because of naming in the cosmix plugin. For example, BBC one is called BBC1 HD in cosmix. Other channels that don't show up: BBC Two, BBC Three, Channel 4, Sky One and probably more.

**Comment by OpenELEQ** [comment]
Think I fixed it, please retry.

**Comment by chiefkes** [comment]
Thanks, seems to work!
